name: fuse-test-snap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A test application to use fuse fs.
description: |
  This is a test application to be used to develop required interfaces
  for snapd.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  fuse-test:
    command: main
    plugs:
      - fuse-support

parts:
  fuse-test:
    source: src
    plugin: make
    build-packages:
      - pkg-config
      - libfuse3-dev
    stage-packages:
      - libfuse3-3
    override-build: |
      gcc -Wall main.c `pkg-config fuse3 --cflags --libs` -o main
      cp $SNAPCRAFT_PART_BUILD/main $SNAPCRAFT_PART_INSTALL/


